
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS skills;

CREATE TABLE students (
id SERIAL PRIMARY KEY,
name VARCHAR (255) UNIQUE
); 

CREATE TABLE skills (
id SERIAL PRIMARY KEY,
skill VARCHAR(255),
proficient boolean,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
); 
 

