INSERT INTO wdi (id, name, description) 

VALUES 
(default, 'lin', 'cola'),
(default, 'ashley', 'cola'),
(default, 'ginny', 'cola'),
(default, 'belizabeth', 'cola'),
(default, 'elizabeth', 'cola'),
(default, 'nada', 'cola'),
(default, 'felix', 'cola'),
(default, 'eren', 'cola'),
(default, 'david', 'cola'),
(default, 'james', 'cola'),
(default, 'franco', 'cola'),
(default, 'luke', 'cola'),
(default, 'bo', 'cola'),
(default, 'tylaine', 'cola'),
(default, 'waseem', 'cola'),
(default, 'kenny', 'cola'),
(default, 'dannee', 'cola'),
(default, 'samantha', 'cola'),
(default, 'jonathan', 'cola'),
(default, 'al', 'cola'),
(default, 'roberto', 'cola'),
(default, 'carol', 'cola'),
(default, 'shawn', 'cola'),
(default, 'william', 'cola'),
(default, 'geoff', 'cola'),
(default, 'genesis', 'cola'),
(default, 'shua', 'cola'),
(default, 'daylan', 'cola');
