INSERT INTO student (name) 

VALUES 
('chris'),
('lin'),
('ashley'),
('ginny'),
('belizabeth'),
('elizabeth'),
('nada'),
('felix'),
('eren'),
('david'),
('james'),
('franco'),
('luke'),
('bo'),
('tylaine'),
('waseem'),
('kenny'),
('dannee'),
('samantha'),
('jonathan'),
('al'),
('roberto'),
('carol'),
('shawn'),
('william'),
('geoff'),
('genesis'),
('shua'),
('daylan');


INSERT INTO skills (skill, student_id)

VALUES 
('dummy', (SELECT id FROM student WHERE student.name = 'chris')),
('dummy', (SELECT id FROM student WHERE student.name = 'lin')),
('dummy', (SELECT id FROM student WHERE student.name = 'ashley')),
('dummy', (SELECT id FROM student WHERE student.name = 'ginny')),
('dummy', (SELECT id FROM student WHERE student.name = 'belizabeth')),
('dummy', (SELECT id FROM student WHERE student.name = 'elizabeth')),
('dummy', (SELECT id FROM student WHERE student.name = 'nada')),
('dummy', (SELECT id FROM student WHERE student.name = 'felix')),
('dummy', (SELECT id FROM student WHERE student.name = 'eren')),
('dummy', (SELECT id FROM student WHERE student.name = 'david')),
('dummy', (SELECT id FROM student WHERE student.name = 'james')),
('dummy', (SELECT id FROM student WHERE student.name = 'franco')),
('dummy', (SELECT id FROM student WHERE student.name = 'luke')),
('dummy', (SELECT id FROM student WHERE student.name = 'bo')),
('dummy', (SELECT id FROM student WHERE student.name = 'tylaine')),
('dummy', (SELECT id FROM student WHERE student.name = 'waseem')),
('dummy', (SELECT id FROM student WHERE student.name = 'kenny')),
('dummy', (SELECT id FROM student WHERE student.name = 'dannee')),
('dummy', (SELECT id FROM student WHERE student.name = 'samantha')),
('dummy', (SELECT id FROM student WHERE student.name = 'jonathan')),
('dummy', (SELECT id FROM student WHERE student.name = 'al')),
('dummy', (SELECT id FROM student WHERE student.name = 'roberto')),
('dummy', (SELECT id FROM student WHERE student.name = 'carol')),
('dummy', (SELECT id FROM student WHERE student.name = 'shawn')),
('dummy', (SELECT id FROM student WHERE student.name = 'william')),
('dummy', (SELECT id FROM student WHERE student.name = 'geoff')),
('dummy', (SELECT id FROM student WHERE student.name = 'genesis')),
('dummy', (SELECT id FROM student WHERE student.name = 'shua')),
('dummy', (SELECT id FROM student WHERE student.name = 'daylan'))
